import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi';
import { z } from 'zod';

extendZodWithOpenApi(z);

// Represents a device in the system
export const iotDeviceResponseSchema = z.object({
  deviceId: z.string(),
  name: z.string(),
  model: z.string().optional(),
  firmwareVersion: z.string().optional(),
  registeredAt: z.string(), // ISO timestamp
  lastSeenAt: z.string().optional(), // ISO timestamp
});

// An event generated by a device
export const eventResponseSchema = z.object({
  eventId: z.string(),
  deviceId: z.string(),
  timestamp: z.string(), // ISO timestamp
  type: z.string(),
  payload: z.any(),
});

// A single device fetched by criteria
export const deviceResponseSchema = z.object({
  deviceId: z.string(),
  serialNumber: z.string(),
  type: z.string(),
  owner: z.string(),
  registeredAt: z.string(),
});

// Shadow alarm settings
export const shadowAlarmSchema = z.object({
  enabled: z.boolean(),
  threshold: z.number(),
  mode: z.enum(['auto', 'manual']).optional(),
});

// Ping / LED light response
export const pingResponseSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
  timestamp: z.string(),
});

// Current status of a device
export const deviceStatusSchema = z.object({
  deviceId: z.string(),
  online: z.boolean(),
  batteryLevel: z.number().min(0).max(100).optional(),
  lastSeenAt: z.string(),
});

// API status by kind
export const apiStatusSchema = z.object({
  kind: z.string(),
  status: z.enum(['ok', 'degraded', 'down']),
  uptimeSeconds: z.number(),
});

// Single entry for a device
export const entryResponseSchema = z.object({
  entryId: z.string(),
  deviceId: z.string(),
  timestamp: z.string(),
  data: z.any(),
});

// Optionally infer TS types
export type IotDevice = z.infer<typeof iotDeviceResponseSchema>;
export type Event = z.infer<typeof eventResponseSchema>;
export type Device = z.infer<typeof deviceResponseSchema>;
export type ShadowAlarm = z.infer<typeof shadowAlarmSchema>;
export type PingResponse = z.infer<typeof pingResponseSchema>;
export type DeviceStatus = z.infer<typeof deviceStatusSchema>;
export type ApiStatus = z.infer<typeof apiStatusSchema>;
export type Entry = z.infer<typeof entryResponseSchema>;
