import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi';
import { z } from 'zod';

extendZodWithOpenApi(z);

// Represents a device in the system
export const iotDeviceResponseSchema = z.object({
  deviceId: z.string().openapi({ example: 'nrf-352656106701140' }),
  name: z.string().openapi({ example: 'Kitchen Display' }),
  model: z.string().optional().openapi({ example: 'OpenPaper 7' }),
  firmwareVersion: z.string().optional().openapi({ example: '1.2.3' }),
  registeredAt: z
    .string()
    .datetime()
    .openapi({ example: '2026-05-21T09:30:00.000Z' }),
  lastSeenAt: z
    .string()
    .datetime()
    .optional()
    .openapi({ example: '2026-05-21T10:15:00.000Z' }),
}).openapi({
  example: {
    deviceId: 'nrf-352656106701140',
    name: 'Kitchen Display',
    model: 'OpenPaper 7',
    firmwareVersion: '1.2.3',
    registeredAt: '2026-05-21T09:30:00.000Z',
    lastSeenAt: '2026-05-21T10:15:00.000Z',
  },
});

// An event generated by a device
export const eventResponseSchema = z.object({
  eventId: z.string().openapi({ example: 'evt_01HX0000000000000000000000' }),
  deviceId: z.string().openapi({ example: 'nrf-352656106701140' }),
  timestamp: z
    .string()
    .datetime()
    .openapi({ example: '2026-05-21T10:15:00.000Z' }),
  type: z.string().openapi({ example: 'state' }),
  payload: z.any().openapi({ example: { battery: 87, online: true } }),
}).openapi({
  example: {
    eventId: 'evt_01HX0000000000000000000000',
    deviceId: 'nrf-352656106701140',
    timestamp: '2026-05-21T10:15:00.000Z',
    type: 'state',
    payload: {
      battery: 87,
      online: true,
    },
  },
});

// A single device fetched by criteria
export const deviceResponseSchema = z.object({
  deviceId: z.string().openapi({ example: 'nrf-352656106701140' }),
  serialNumber: z.string().openapi({ example: 'nrf-352656106701140' }),
  type: z.string().openapi({ example: 'paper-display' }),
  owner: z.string().openapi({ example: '682fd0d7d4a6325d9d45b86e' }),
  registeredAt: z
    .string()
    .datetime()
    .openapi({ example: '2026-05-21T09:30:00.000Z' }),
}).openapi({
  example: {
    deviceId: 'nrf-352656106701140',
    serialNumber: 'nrf-352656106701140',
    type: 'paper-display',
    owner: '682fd0d7d4a6325d9d45b86e',
    registeredAt: '2026-05-21T09:30:00.000Z',
  },
});

// Shadow alarm settings
export const shadowAlarmSchema = z.object({
  enabled: z.boolean().openapi({ example: true }),
  threshold: z.number().openapi({ example: 80 }),
  mode: z.enum(['auto', 'manual']).optional().openapi({ example: 'auto' }),
}).openapi({
  example: {
    enabled: true,
    threshold: 80,
    mode: 'auto',
  },
});

// Ping / LED light response
export const pingResponseSchema = z.object({
  success: z.boolean().openapi({ example: true }),
  message: z.string().optional().openapi({ example: 'Device responded' }),
  timestamp: z
    .string()
    .datetime()
    .openapi({ example: '2026-05-21T10:15:00.000Z' }),
}).openapi({
  example: {
    success: true,
    message: 'Device responded',
    timestamp: '2026-05-21T10:15:00.000Z',
  },
});

// Current status of a device
export const deviceStatusSchema = z.object({
  deviceId: z.string().openapi({ example: 'nrf-352656106701140' }),
  online: z.boolean().openapi({ example: true }),
  batteryLevel: z.number().min(0).max(100).optional().openapi({ example: 87 }),
  lastSeenAt: z
    .string()
    .datetime()
    .openapi({ example: '2026-05-21T10:15:00.000Z' }),
}).openapi({
  example: {
    deviceId: 'nrf-352656106701140',
    online: true,
    batteryLevel: 87,
    lastSeenAt: '2026-05-21T10:15:00.000Z',
  },
});

// API status by kind
export const apiStatusSchema = z.object({
  kind: z.string().openapi({ example: 'iot' }),
  status: z.enum(['ok', 'degraded', 'down']).openapi({ example: 'ok' }),
  uptimeSeconds: z.number().openapi({ example: 86400 }),
}).openapi({
  example: {
    kind: 'iot',
    status: 'ok',
    uptimeSeconds: 86400,
  },
});

// Single entry for a device
export const entryResponseSchema = z.object({
  entryId: z.string().openapi({ example: 'entry_01HX0000000000000000000000' }),
  deviceId: z.string().openapi({ example: 'nrf-352656106701140' }),
  timestamp: z
    .string()
    .datetime()
    .openapi({ example: '2026-05-21T10:15:00.000Z' }),
  data: z.any().openapi({ example: { state: 'active' } }),
}).openapi({
  example: {
    entryId: 'entry_01HX0000000000000000000000',
    deviceId: 'nrf-352656106701140',
    timestamp: '2026-05-21T10:15:00.000Z',
    data: {
      state: 'active',
    },
  },
});

// Optionally infer TS types
export type IotDevice = z.infer<typeof iotDeviceResponseSchema>;
export type Event = z.infer<typeof eventResponseSchema>;
export type Device = z.infer<typeof deviceResponseSchema>;
export type ShadowAlarm = z.infer<typeof shadowAlarmSchema>;
export type PingResponse = z.infer<typeof pingResponseSchema>;
export type DeviceStatus = z.infer<typeof deviceStatusSchema>;
export type ApiStatus = z.infer<typeof apiStatusSchema>;
export type Entry = z.infer<typeof entryResponseSchema>;
