import { Router } from "express";
import buildRouterAndDocs from "../utils/buildRouterAndDocs.js";
import type { RouteSpec } from "../types/routeSpec";
import auth from "../middlewares/auth.js";
import {
  validateBodyOrganization,
  validateQueryOrganization,
} from "../middlewares/validateOrganization.js";
import { validateQuerySearchUserAndOrganization } from "../middlewares/validateQuerySearchUserAndOrganization.js";
import { validateDevice } from "../middlewares/validateDevice.js";
import { validateDeviceUserOrganization } from "../middlewares/validateDeviceUserOrganization.js";
import * as devicesController from "./devices.controller.js";
import { resetDevice } from "./devices.controller.js";
import {
  createDeviceSchema,
  queryDevicesSchema,
  getDeviceSchema,
  updateDeviceSchema,
  deleteDeviceSchema,
  getEventsSchema,
  pingDeviceSchema,
  registerDeviceSchema,
  ledLightSchema,
  rebootDeviceSchema,
  resetDeviceSchema,
} from "./devices.validation.js";
import {
  deviceResponseSchema,
  devicesResponseSchema,
  eventResponseSchema,
  genericResponseSchema,
  resetResponseSchema,
} from "./devices.schemas.js";
import {
  validateOrganizationDelete,
  validateOrganizationUpdate,
} from "../middlewares/validateAction.js";

export const devicesRouteSpecs: RouteSpec[] = [
  {
    method: "post",
    path: "/",
    validate: [
      auth("manageUsers"),
      validateBodyOrganization,
      validateOrganizationDelete,
    ],
    requestSchema: createDeviceSchema,
    responseSchema: deviceResponseSchema,
    handler: devicesController.createEntry,
    summary: "Create a new device",
    description:
      "Create a new device and associate it with the current organization.",
  },
  {
    method: "get",
    path: "/",
    validate: [auth("getUsers"), validateQuerySearchUserAndOrganization],
    requestSchema: queryDevicesSchema,
    responseSchema: devicesResponseSchema,
    handler: devicesController.queryDevicesByUser,
    summary: "Query devices by user",
    description:
      "Retrieve a paginated list of devices visible to the authenticated user.",
  },
  {
    method: "get",
    path: "/events/:deviceId",
    validate: [auth("getUsers"), validateDevice],
    requestSchema: getEventsSchema,
    responseSchema: eventResponseSchema.array(),
    handler: devicesController.getEvents,
    summary: "Get events for a device",
    description:
      "Fetch a chronological list of events generated by the specified device.",
  },
  {
    method: "get",
    path: "/:deviceId",
    validate: [auth("getUsers"), validateDevice],
    requestSchema: getDeviceSchema,
    responseSchema: deviceResponseSchema,
    handler: devicesController.getEntry,
    summary: "Get a device by ID",
    description:
      "Retrieve detailed information for the device identified by its ID.",
  },
  {
    method: "post",
    path: "/:deviceId",
    validate: [auth("manageUsers"), validateDevice, validateOrganizationUpdate],
    requestSchema: updateDeviceSchema,
    responseSchema: deviceResponseSchema,
    handler: devicesController.updateEntry,
    summary: "Update a device",
    description:
      "Modify the properties of an existing device identified by its ID.",
  },
  {
    method: "delete",
    path: "/:deviceId",
    validate: [auth("manageUsers"), validateDevice, validateOrganizationDelete],
    requestSchema: deleteDeviceSchema,
    responseSchema: genericResponseSchema,
    handler: devicesController.deleteEntry,
    summary: "Delete a device",
    description: "Remove the specified device from the system.",
  },
  {
    method: "post",
    path: "/registerdevice/:deviceId",
    validate: [
      auth("getUsers"),
      validateBodyOrganization,
      validateOrganizationDelete,
    ],
    requestSchema: registerDeviceSchema,
    responseSchema: genericResponseSchema,
    handler: devicesController.registerDevice,
    summary: "Register a device",
    description:
      "Associate an existing device with the authenticated organization.",
  },
  {
    method: "post",
    path: "/ledlight/:deviceId",
    validate: [auth("getUsers"), validateDevice],
    requestSchema: ledLightSchema,
    responseSchema: genericResponseSchema,
    handler: devicesController.ledLight,
    summary: "Set LED light on device",
    description:
      "Turn the device’s LED on or off, or set its color/brightness.",
    memoOnly: true,
  },
  {
    method: "get",
    path: "/ping/:deviceId",
    validate: [auth("getUsers"), validateDevice],
    requestSchema: pingDeviceSchema,
    responseSchema: genericResponseSchema,
    handler: devicesController.pingDevice,
    summary: "Ping a device",
    description:
      "Check connectivity and round-trip time to the specified device.",
  },
  {
    method: "post",
    path: "/reset/:deviceId",
    validate: [auth("getUsers"), validateDevice, validateOrganizationDelete],
    requestSchema: resetDeviceSchema,
    responseSchema: resetResponseSchema,
    handler: resetDevice,
    summary: "Reset the sensors of a device",
    description:
      "Remotely reset all sensors on the target device to factory defaults.",
  },
  {
    method: "post",
    path: "/reboot/:deviceId",
    validate: [auth("getUsers"), validateDevice, validateOrganizationDelete],
    requestSchema: rebootDeviceSchema,
    responseSchema: genericResponseSchema,
    handler: devicesController.rebootDevice,
    summary: "Reboot a device",
    description: "Initiate a remote reboot of the specified device.",
  },
];

const router: Router = Router();
buildRouterAndDocs(router, devicesRouteSpecs, "/devices", ["Devices"]);

export default router;
